### ISSUE TITLE
useless project so far

### ISSUE THREAD

**Issue by makerGeek** [RocketChat/Rocket.Chat.PWA.React#11]
![selection_250](https://user-images.githubusercontent.com/15243070/32703775-06bfaaba-c7fb-11e7-89f7-08375181018b.png)

**Comment by manuelLandreau** [comment]
You need to git checkout to the login-component branch

**Comment by inf3cti0n95** [comment]
@makerGeek Checkout the login-component branch for now. It has to be reviewed before merging into the master branch

**Comment by inf3cti0n95** [comment]
@makerGeek I've merged the development branch ie the login-component branch onto the master branch for the newcomers to contribute to.

**Comment by sscholl** [comment]
Interessting Project. Is that the app, that is available under the Google Play Store?
What do you think how far you have come, how long will it take to have the same functionality as the other apps?
